version: "3.8"

services:
  hesap_api:
    build: ./hesap_api
    container_name: hesap_api
    ports:
      - "5000:5000"

  client_api:
    build: ./client_api
    container_name: client_api
    ports:
      - "8000:6000"   # ✅ DIŞARDA 8000, İÇERİDE 6000
    depends_on:
      - hesap_api

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - client_api

